gnu: emacs-powerline: Update to c35c35b to fix circular-list error.
* gnu/packages/emacs-xyz.scm (emacs-powerline): Update to
c35c35bdf5ce2d992882c1f06f0f078058870d4a.

Building with native-comp `guix build --with-input=emacs-minimal=emacs` fails
with:
  Error: circular-list (".../powerline.el" ...)

This bump pulls in upstream commit containign the fix.

Change-Id: I2e5ba043c362e4bf1ebc114a3dc92e81e783f807