gnu: insight-toolkit: Fix Python module and add a test for it.
Insight Toolkit (ITK) Python module fails to import due to:
  AttributeError: module 'numpy' has no attribute 'bool'
Implement the fix from here:
<https://github.com/InsightSoftwareConsortium/ITK/pull/5402>

While ITK's test suite is disabled for good reason, we can test that the
Python module imports successfully.  Importing the Python module requires
NumPy.  It is added as a native-input instead of a propagated-input because
the "out" output is unrelated to Python.

* gnu/packages/image-processing.scm (insight-toolkit)[arguments]: Remove
'#tests? #f'.  Add #:imported-modules and #:modules.
<#:phases>: Delete 'check.  Add 'fix-numpy-bool and 'python-sanity-check.
[native-inputs]: Add python-numpy.
(insight-toolkit-legacy)[arguments]: Remove inherited phase
'python-sanity-check.
[native-inputs]: Remove inherited python-numpy.

Change-Id: Ia6d14c22cbea9cd9877da36f8f72e2e34ff8a8a6
Signed-off-by: Andreas Enge <andreas@enge.fr>