gnu: automake-1.16.5: Skip tests.
As 23 compiler "tap" tests fail that cannot be easily skipped, disable tests
altogether.

    ERROR: t/depcomp-auto
    =====================

    ERROR: t/depcomp-auto.tap - missing test plan
    ERROR: t/depcomp-auto.tap - exited with status 77

    ERROR: t/depcomp-cpp
    ====================

    ERROR: t/depcomp-cpp.tap - missing test plan
    ERROR: t/depcomp-cpp.tap - exited with status 77

    ERROR: t/depcomp-dashmstdout
    ============================

    ERROR: t/depcomp-dashmstdout.tap - missing test plan
    ERROR: t/depcomp-dashmstdout.tap - exited with status 77

    ERROR: t/depcomp-gcc
    ====================

    ERROR: t/depcomp-gcc.tap - missing test plan
    ERROR: t/depcomp-gcc.tap - exited with status 77

* gnu/packages/autotools.scm (automake)[arguments]: Skip tests.  Remove
"skip-test" phase, as the "tap" tests ERROR out when skipped.
(automake)[arguments]: Enable tests.  Add, instead of replace, "skip-tests" phase.

Change-Id: Iacc2ca3bc84f0a4b261663b9178922bcb1c18578